site_name: bms v2025.3 DOCUMENTATION

site_dir: ../docs/

markdown_extensions:
#     - pymdownx.highlight
#     - pymdownx.inlinehilite
    - pymdownx.tabbed:
        alternate_style: true
#     - pymdownx.snippets
#     - pymdownx.critic
#     - pymdownx.caret
#     - pymdownx.keys
#     - pymdownx.mark
#     - pymdownx.tilde
#     - attr_list
#     - md_in_html
    - admonition
#     - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
#     - tables
#     - pymdownx.emoji:
#         emoji_index: !!python/name:materialx.emoji.twemoji
#         emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
 - git-revision-date
 - search
 - markmap
#  - mkdocs-video

dev_addr: '172.30.72.43:8002'

theme:
    name: material
    features:
      - search.suggest
      - search.highlight
      - search.share
    #name: readthedocs
#     logo: favicon.png
#     custom_dir: overrides
#     highlightjs: true
#     palette:
#         primary: black
#         scheme: default
#     features:
#         - navigation.tabs
#         - navigation.top
#         - content.tabs.link

nav:
    - index.md
    - 2025.3 Version:
        - home: bms/2025.3/index.md
        - C Language:
            - void *bms_create(): bms/2025.3/_bms_create.md
            - bms_free(): bms/2025.3/_bms_free.md
            - bms_seek(): bms/2025.3/_bms_seek.md
            - bms_read_write(): bms/2025.3/_bms_read_write.md
            - bms_error(): bms/2025.3/_bms_error.md
            - bms_version(): bms/2025.3/_bms_version.md
        - Assembly language:
            - bms_create: bms/2025.3/bms_create.md
            - bms_free: bms/2025.3/bms_free.md
            - bms_seek: bms/2025.3/bms_seek.md
            - bms_read_write: bms/2025.3/bms_read_write.md
            - bms_error: bms/2025.3/bms_error.md
            - bms_version: bms/2025.3/bms_version.md

# extra_css:
#     - stylesheets/extra.css
# extra:
#     social:
#         - icon: fontawesome/brands/twitter
#           link: https://twitter.com/OrixTwil
#         - icon: fontawesome/brands/youtube
#           link: https://www.youtube.com/user/jede06600/videos